"""
Note: This file was generated by an LLM.
"""

import numpy as np

def calculate_caf(received_signal, reference_signal, max_delay_samples=500):
    """
    Computes the Cross-Ambiguity Function (CAF) matrix.
    Rows = Time Delays (Range / Path Length)
    Columns = Doppler Frequency Shifts
    note: max_delay_samples is how far in each direction the function should look for time delay
    """
    # Create the 2D matrix grid to hold our CAF values
    # Rows: up to our max time delay guess
    # Columns: exactly equal to the length of our signal
    caf_matrix = np.zeros((max_delay_samples, len(reference_signal)), dtype=complex)
    
    print("Calculating Cross-Ambiguity Function Matrix...")
    
    # Loop over every possible time delay (Range search)
    for tau in range(max_delay_samples):
        # 1. Shift the reference signal in time by 'tau' samples
        x_shifted = np.roll(reference_signal, tau)
        
        # 2. Conjugate multiply: mixes the received signal with our shifted reference
        # multiplying complex numbers (e^(i*theta)) combines their frequencies!
        # (because dynamic angle changes, or theta, are being added)
        mixed_signal = received_signal * np.conj(x_shifted)
        
        # 3. FFT calculates all possible Doppler frequency shifts for this row instantly
        caf_matrix[tau, :] = np.fft.fft(mixed_signal)
        
    # Center the Doppler frequencies so 0 Hz is right in the middle
    caf_matrix = np.fft.fftshift(caf_matrix, axes=1)
    
    # Return the absolute magnitude (the energy profile of the signal)
    return np.abs(caf_matrix)


def extract_radar_peaks(caf_magnitude, sample_rate, signal_length):
    """
    Finds the exact coordinate of the strongest ionospheric peak in the matrix.
    """
    # Find the row (delay) and column (doppler) index of the maximum value
    delay_idx, doppler_idx = np.unravel_index(np.argmax(caf_magnitude), caf_magnitude.shape)
    
    # Convert the column index back into a real-world Doppler frequency (Hz)
    frequencies = np.fft.fftfreq(signal_length, 1 / sample_rate)
    frequencies = np.fft.fftshift(frequencies)
    detected_doppler = frequencies[doppler_idx]
    
    return delay_idx, detected_doppler